add_newline = false
command_timeout = 5000

format = """\
$directory\
$character"""

right_format = """\
$status\
$cmd_duration\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$time"""

[directory]
read_only = ' w!'
read_only_style = 'yellow'
truncate_to_repo = false
truncation_symbol = '_/'
style = 'cyan'

[character]
success_symbol = '[>](green)'
error_symbol = '[>](bold red)'
vimcmd_symbol = '[<](green)'
vimcmd_replace_one_symbol = '[r](bold purple)'
vimcmd_replace_symbol = '[R](bold purple)'
vimcmd_visual_symbol = '[v](bold purple)'

[status]
disabled = false
format = '[($signal_name/)$status]($style) '
pipestatus = true
pipestatus_format = '[$pipestatus]($style) '
pipestatus_segment_format = '[($signal_name/)$status]($style)'
style = 'bold red'

[cmd_duration]
min_time = 1000
style = 'cyan'
format = '[$duration]($style) '

[git_commit]
tag_symbol = '#'
commit_hash_length = 4
style = 'green'

[git_state]
format = '[$state($progress_current/$progress_total)]($style) '
style = 'yellow'

[git_status]
format = '($conflicted$stashed$ahead_behind[$untracked]($style) )'
conflicted = '[!!](bold red)'
ahead = '[$count>](green)'
behind = '[$count<](green)'
stashed = "[$count$](green)"
diverged = '[Y]($style)[$ahead_count>$behind_count<](green)'
renamed = 'r'
deleted = 'x'
style = 'yellow'

[git_metrics]
disabled = false
added_style = 'green'
deleted_style = 'yellow'

[git_branch]
symbol = ''
truncation_length = 16
truncation_symbol = '~'
style = 'purple'
format = '[$symbol$branch(:$remote_branch)]($style) '

[time]
disabled = false
format = '[$time]($style)'
time_format = '%R'
utc_time_offset = 'local'
style = 'dimmed white'
